@startuml

component "Terminal Calypso Card API\n[CNA-TCC-API]" as TCC
component "Terminal Calypso Crypto\nSymmetric API (this specification)" as TCCS #LightYellow
component "Symmetric Crypto Module\n(SAM or equivalent)" as Mod

TCC --> TCCS : delegates crypto
TCCS --> Mod : implemented by
@enduml
