@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Calypso Crypto Symmetric API 0.1.+ (2023-11-06)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB937F
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

package "calypso.crypto.symmetric" as api {
    class "SymmetricCryptoApiProperties" as ApiProperties <<constants>> <<green>> {
        +const VERSION: String = "0.1"
    }
    package spi {
        interface SymmetricCryptoCardTransactionManagerFactorySpi <<red>> {
            +isExtendedModeSupported() → Boolean
            +getMaxCardApduLengthSupported() → Int

            +preInitTerminalSessionContext() → Unit
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
    
            +createCardTransactionManager(cardKeyDiversifier: ByteArray, useExtendedMode: Boolean, transactionAuditData: List<ByteArray>) → SymmetricCryptoCardTransactionManagerSpi
        }
        interface SymmetricCryptoCardTransactionManagerSpi <<red>> {
            +initTerminalSecureSessionContext() → ByteArray
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
            +initTerminalSessionMac(openSecureSessionDataOut: ByteArray, kif: Byte, kvc: Byte) → Unit
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
            +updateTerminalSessionMac(cardApdu: ByteArray) → ByteArray?
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
            +finalizeTerminalSessionMac() → ByteArray
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
    
            +generateTerminalSessionMac() → ByteArray
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
    
            +activateEncryption() → Unit
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
            +deactivateEncryption() → Unit
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
    
            +isCardSessionMacValid(cardSessionMac: ByteArray) → Boolean
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
    
            +computeSvCommandSecurityData(data: SvCommandSecurityDataApi) → Unit
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
            +isCardSvMacValid(cardSvMac: ByteArray) → Boolean
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
    
            +cipherPinForPresentation(cardChallenge: ByteArray, pin: ByteArray, kif: Byte, kvc: Byte) → ByteArray
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
            +cipherPinForModification(cardChallenge: ByteArray, currentPin: ByteArray, newPin: ByteArray, kif: Byte, kvc: Byte) → ByteArray
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
            +generateCipheredCardKey(cardChallenge: ByteArray, issuerKeyKif: Byte, issuerKeyKvc: Byte, targetKeyKif: Byte, targetKeyKvc: Byte) → ByteArray
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>

            +synchronize() → Unit
            {method} <size:10><color:#7F8C8D>    ⚠ errors: SymmetricCrypto, SymmetricCryptoIO</color></size>
        }
    }
    exception "SymmetricCrypto\nSymmetricCryptoIO" as errors <<error>> <<green>> {
        +val message: String
        +val cause: Any?
    }
    interface SvCommandSecurityDataApi {
        +getSvGetRequest() → ByteArray
        +getSvGetResponse() → ByteArray
        +getSvCommandPartialRequest() → ByteArray

        +setSerialNumber(serialNumber: ByteArray) → SvCommandSecurityDataApi
        +setTransactionNumber(transactionNumber: ByteArray) → SvCommandSecurityDataApi
        +setTerminalChallenge(terminalChallenge: ByteArray) → SvCommandSecurityDataApi
        +setTerminalSvMac(terminalSvMac: ByteArray) → SvCommandSecurityDataApi
    }
}

' Associations

SymmetricCryptoCardTransactionManagerFactorySpi ..> SymmetricCryptoCardTransactionManagerSpi #C_LINK : provide >

SymmetricCryptoCardTransactionManagerSpi .left.> SvCommandSecurityDataApi #C_USE : use >

' == LAYOUT ==

SymmetricCryptoCardTransactionManagerSpi .[hidden]. errors

' == STYLE ==

package api #C_GREY1 {}
package api.spi #C_GREY2 {}

@enduml