@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Calypso Crypto Symmetric API 0.1.+ (2023-11-06)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

package "calypso.crypto.symmetric" as api {
    +class "**final** SymmetricCryptoApiProperties" as ApiProperties <<green>> {
        +{static} **final** VERSION: string
    }
    package spi {
        +interface SymmetricCryptoCardTransactionManagerFactorySpi <<red>> {
            +isExtendedModeSupported() -> boolean
            +getMaxCardApduLengthSupported() -> integer

            +preInitTerminalSessionContext() -> unit
    
            +createCardTransactionManager(cardKeyDiversifier: byte array, useExtendedMode: boolean, transactionAuditData: list<byte array>) -> SymmetricCryptoCardTransactionManagerSpi
        }
        +interface SymmetricCryptoCardTransactionManagerSpi <<red>> {
            +initTerminalSessionContext() -> byte array
            +initTerminalSessionMac(openSecureSessionDataOut: byte array, kif: byte, kvc: byte) -> unit
            +updateTerminalSessionMac(cardApdu: byte array) -> byte array?
            +finalizeTerminalSessionMac() -> byte array
    
            +generateTerminalSessionMac() -> byte array
    
            +activateEncryption() -> unit
            +deactivateEncryption() -> unit
    
            +isCardSessionMacValid(cardSessionMac: byte array) -> boolean
    
            +computeSvCommandSecurityData(data: SvCommandSecurityDataApi) -> unit
            +isCardSvMacValid(cardSvMac: byte array) -> boolean
    
            +cipherPinForPresentation(cardChallenge: byte array, pin: byte array, kif: byte, kvc: byte) -> byte array
            +cipherPinForModification(cardChallenge: byte array, currentPin: byte array, newPin: byte array, kif: byte, kvc: byte) -> byte array
            +generateCipheredCardKey(cardChallenge: byte array, issuerKeyKif: byte, issuerKeyKvc: byte, targetKeyKif: byte, targetKeyKvc: byte) -> byte array

            +synchronize() -> unit
        }
    }
    +class "<<Exception>>\nSymmetricCryptoException" as SymmetricCryptoException <<green>> {
    }
    +class "<<Exception>>\nSymmetricCryptoIOException" as SymmetricCryptoIOException <<green>> {
    }
    +interface SvCommandSecurityDataApi {
        +getSvGetRequest() -> byte array
        +getSvGetResponse() -> byte array
        +getSvCommandPartialRequest() -> byte array

        +setSerialNumber(serialNumber: byte array) -> SvCommandSecurityDataApi
        +setTransactionNumber(transactionNumber: byte array) -> SvCommandSecurityDataApi
        +setTerminalChallenge(terminalChallenge: byte array) -> SvCommandSecurityDataApi
        +setTerminalSvMac(terminalSvMac: byte array) -> SvCommandSecurityDataApi
    }
}

' Associations

SymmetricCryptoCardTransactionManagerFactorySpi ..> SymmetricCryptoCardTransactionManagerSpi #C_LINK : provide >

SymmetricCryptoCardTransactionManagerSpi .left.> SvCommandSecurityDataApi #C_USE : use >

' == LAYOUT ==

SymmetricCryptoCardTransactionManagerSpi .[hidden]. SymmetricCryptoException
SymmetricCryptoCardTransactionManagerSpi .[hidden]. SymmetricCryptoIOException

' == STYLE ==

package api #C_GREY1 {}
package api.spi #C_GREY2 {}

@enduml